#%RAML 1.0 DataType
type: object
displayName: Sync Next Data Type
description: Used to return next sync begin/end date window for data sync operations.
properties:
  syncDateBegin: 
    type: datetime
    description: The "begin" window to perform data sync operations.    
  syncDateEnd:
    type: datetime    
    description: The "begin" window to perform data sync operations.
