#%RAML 1.0 DataType
description: Time range
type: object
properties: 
  startTime: 
    description: service starttime
    type: time-only
    required: true
  endTime: 
    description: service endtime
    type: time-only
    required: true